GET http://localhost:3001

###

GET http://localhost:3001/Pizza

###

GET http://localhost:3001/Pizza/66150402e4a664bc4c9a9360


###

POST http://localhost:3001/Pizza
Content-Type: application/json

{
    "name": "Calzone",
    "base": "Tomate",
    "price": 4,
    "ingredients": ["Sauce Tomate", "Mozzarella", "Jambon", "Champignons", "Œuf"],
    "description": "Une pizza pliée en forme de chausson garnie de sauce tomate, de mozzarella, de jambon, de champignons et d'œuf.",
    "rating": 6,
    "available": true,
    "size": ["Moyenne", "Grande"],
    "allergens": ["Gluten", "Produits Laitiers", "Œuf"]
}

###

PUT http://localhost:3001/Pizza/66150c79375dc34fe2367284
Content-Type: application/json

{
    "name": "nordique",
    "base": "Tomate",
    "price": 10.99,
    "ingredients": ["Sauce Tomate", "Mozzarella", "Saumon", "Crevettes", "Aneth"],
    "description": "Une pizza garnie de sauce tomate, de mozzarella, de saumon, de crevettes et d'aneth.",
    "rating": 4.5,
    "available": true,
    "size": ["Moyenne", "Grande"],
    "allergens": ["Gluten", "Produits Laitiers", "Poisson", "Crustacés"]
}

###
DELETE http://localhost:3001/Pizza/66150c79375dc34fe2367284


### 

POST http://localhost:3001/auth/signin
Content-Type: application/json

{
    "email": "mehdi.terrane@gmail.com",
    "password": "Mzzzz?21"
}

###

POST http://localhost:3001/auth/signup
Content-Type: application/json

{
    "email": "mehdi.terrane@gmail.com",
    "password": "Mzzzz?21",
    "name": "mehdi",
    "phoneNumber": "0606060606"
}