version: "3.1"

services:
  adminer:
    image: arm64v8/adminer
    restart: always
    ports:
      - 8080:8080

  db:
    image: arm64v8/mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
