import { Affiche_tableau, Premier_jour_semaine, Somme_tableau, Ajout_fruits, Moyenne_notes, recherche_oiseau, Pays_order_decreasing, Troisieme_mois, Value_min_max, Phrase_longue } from "./src/utils/Tableau.js";

const tableau = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
const jours_semaine = ["lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche"];
const tableau_pair = [2, 4, 6, 8, 10];
const tableau_fruits = ["pomme", "banane", "orange", "fraise", "kiwi"];
const fruits = "mangue";
const tableau_oiseaux = ["rouge-gorge", "mésange", "moineau", "rouge-queue", "roucoule", "pigeon"];
const oiseau = "roucoule";
const tableau_pays = ["France", "Allemagne", "Espagne", "Italie", "Portugal", "Suisse", "Belgique", "Luxembourg", "Pays-Bas"];
const mois_année = ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"];
const tableau_valeur_aleatoire = [4, 1, 30, 3, 17, 76, 15, 18, 50];
const tableau_phrase = ["Bonjout tout le monde", "Je suis un développeur", "Je suis en formation", "Je suis en train de coder", "Je suis en train de m'amuser"];

console.log("");
console.log("");
console.log("Tableau.md");
console.log("");
console.log("");
console.log("Exercice 1: ");
console.log(Affiche_tableau(tableau));
console.log("");
console.log("");
console.log("Exercice 2: ");
console.log(Premier_jour_semaine(jours_semaine));
console.log("");
console.log("");
console.log("Exercice 3: ");
console.log(Somme_tableau(tableau_pair));
console.log("");
console.log("");
console.log("Exercice 4: ");
console.log(Ajout_fruits(tableau_fruits, fruits));
console.log("");
console.log("");
console.log("Exercice 5: ");
console.log(Moyenne_notes(tableau));
console.log("");
console.log("");
console.log("Exercice 6:");
console.log(recherche_oiseau(tableau_oiseaux, oiseau));
console.log("");
console.log("");
console.log("Exercice 7: ");
console.log(Pays_order_decreasing(tableau_pays));
console.log("");
console.log("");
console.log("Exercice 8: ");
console.log(Troisieme_mois(mois_année));
console.log("");
console.log("");
console.log("Exercice 9: ");
console.log(Value_min_max(tableau_valeur_aleatoire));
console.log("");
console.log("");
console.log("Exercice 10: ");
console.log(Phrase_longue(tableau_phrase));
